# Generated by Django 5.0.2 on 2024-02-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_logo', models.ImageField(blank=True, upload_to='logos/')),
                ('committee_name', models.CharField(max_length=255)),
                ('head_tuf_id', models.CharField(blank=True, help_text='Roll number of the committee head.', max_length=20, null=True)),
                ('committee_members_tuf_id', models.TextField(blank=True, help_text='Enter comma-separated roll numbers of committee members.', null=True)),
                ('committee_members_names', models.TextField(blank=True, help_text='Enter comma-separated names of committee members.', null=True)),
                ('committee_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('admin_approval', models.BooleanField(default=False)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='event_documents/')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('tuf_id', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('committees', models.ManyToManyField(blank=True, related_name='committee_participants', to='events.committee')),
                ('events_participated', models.ManyToManyField(blank=True, related_name='event_participants', to='events.event')),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_managed', to='events.student')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_committee', to='events.student'),
        ),
    ]
