# Generated by Django 5.0.2 on 2024-02-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_committee_approved_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='approved_events',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='pending_events',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='rejected_events',
        ),
    ]
