# Generated by Django 5.0.2 on 2024-02-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='committee_members_names',
            new_name='committee_members',
        ),
        migrations.RemoveField(
            model_name='student',
            name='manager_id',
        ),
        migrations.AlterField(
            model_name='committee',
            name='committee_head',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
