# Generated by Django 5.0.2 on 2024-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_committee_members_names_committee_committee_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='approved_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committee',
            name='pending_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committee',
            name='rejected_events',
            field=models.IntegerField(default=0),
        ),
    ]
