# Generated by Django 5.0.2 on 2024-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_committee_approved_events_committee_pending_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='approved_events',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='pending_events',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='rejected_events',
        ),
        migrations.AddField(
            model_name='committee',
            name='approved_events',
            field=models.ManyToManyField(blank=True, related_name='approved_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='committee',
            name='pending_events',
            field=models.ManyToManyField(blank=True, related_name='pending_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='committee',
            name='rejected_events',
            field=models.ManyToManyField(blank=True, related_name='rejected_events', to='events.event'),
        ),
    ]
